# 日志设置
logger:
  level: "all"
  stdout: true
# ----------------------------------------------------------------
# 服务器设置
server:
  address: ":3265" # 监听端口
  openapiPath: "/_api.json"
  swaggerPath: "/_swagger"
# ----------------------------------------------------------------
# oh-my-duo 设置
ohmyduo:
  rootDir: "/ohmyduo" # OhMyDuo 服务器 URL 地址前缀
